### PR TITLE
[Workflow] move files to elements

### LINKED ISSUE #1449: [Data Object Editor] Submitting workflow fails
Image

### LINKED ISSUE #1489: [Element Editors] Move workflow related files to element namespace
Currently e.g. `use-workflow.ts` (and some other related files) are in the asset folder. We need to move them to the element folder as they are used for all element types.

### PR DESCRIPTION
**Pull request by xIrusux**
## Changes in this pull request
Resolves #1489 
Resolves #1449 

## Additional info
This pull request refactors the workflow-related components for asset, document, and data object editors by consolidating and relocating shared workflow logic and UI components into a common `element/editor/shared-components/workflow` directory. This change reduces code duplication and improves maintainability by ensuring all editors use the same workflow implementation.

**Workflow component consolidation and relocation:**

* Moved workflow modal, provider, menu, and related hooks from `asset/editor/toolbar/workflow-...` to `element/editor/shared-components/workflow/...`, updating all relevant import paths across asset, document, and data object editors to reference the new shared location. [[1]](diffhunk://#diff-e23a7e6ed44ef7c75b91d90561acda38cb668a9d478e7ef8c533a63646a96df9L15-R16) [[2]](diffhunk://#diff-2d7856ce20ba227042a1382edc3c22665f074458af03a5e1d63b2a2162a8427fL14-R15) [[3]](diffhunk://#diff-bd3dc14fb13b37b5fad23b642c3c4368fb71ba32bda47a8855f885fe03961febL33-R33) [[4]](diffhunk://#diff-faeadcab506b89ac9a1d1968d556de0893360ec77291b81716def9a5485f3243L23-R23) [[5]](diffhunk://#diff-eac44d3ca0bce8873c7816868f85c64df53c00bb12324f4612b5efb56ef84afdL15-R16) [[6]](diffhunk://#diff-bea93ce30a6591ac02edafbc55930343d7b39a88c8e73b1863b2cf0d59c0c186L29-R29) [[7]](diffhunk://#diff-00560af37df5522140d732419f3b18a423b047fa2f25d0b71c125849fe65b0e7L15-R16) [[8]](diffhunk://#diff-f3af4d46cdf718ccbb0971e241c766fba819c86de7510c64d421da1ea0892bffL20-R20) [[9]](diffhunk://#diff-667583dd35e8c06f5a32e52e439a627d6f8729f490abd8c0934d6e6bb802220dL15-R15) [[10]](diffhunk://#diff-33315648551fec1be46676d1557feb4de221a77cb3e1142f46a93f93147dd82eL17-R21) [[11]](diffhunk://#diff-8570df6911db847d6610301744d66230af56e0648bb39324994258e72418ad8bL12-R12) [[12]](diffhunk://#diff-3998f38bf19e8838058a15f988ae7a3d1dafb2038f61d8aeda1027eeebd3179dL17-R21) [[13]](diffhunk://#diff-42fa09d638021e08ce4588196170bb87bd8029dce253fd453c2ecbe61346aab6L16-R19) [[14]](diffhunk://#diff-4600c24e0ee8276c55f48e8b85cb62808ad5cd58a54d2faa5630c8386c5724baL17-R19)

**Hook and style import updates:**

* Updated all hook and style imports in workflow-related components (such as `use-workflow`, `use-submit-workflow`, and style files) to point to the new shared location, ensuring consistency and preventing import errors. [[1]](diffhunk://#diff-f3af4d46cdf718ccbb0971e241c766fba819c86de7510c64d421da1ea0892bffL20-R20) [[2]](diffhunk://#diff-667583dd35e8c06f5a32e52e439a627d6f8729f490abd8c0934d6e6bb802220dL15-R15) [[3]](diffhunk://#diff-33315648551fec1be46676d1557feb4de221a77cb3e1142f46a93f93147dd82eL17-R21) [[4]](diffhunk://#diff-8570df6911db847d6610301744d66230af56e0648bb39324994258e72418ad8bL12-R12) [[5]](diffhunk://#diff-3998f38bf19e8838058a15f988ae7a3d1dafb2038f61d8aeda1027eeebd3179dL17-R21) [[6]](diffhunk://#diff-42fa09d638021e08ce4588196170bb87bd8029dce253fd453c2ecbe61346aab6L16-R19)

**Component registry and editor integration:**

* Registered and integrated the relocated workflow components in the asset, document, and data object editors, ensuring all editors utilize the shared workflow menu, modal, and provider. [[1]](diffhunk://#diff-bd3dc14fb13b37b5fad23b642c3c4368fb71ba32bda47a8855f885fe03961febL33-R33) [[2]](diffhunk://#diff-faeadcab506b89ac9a1d1968d556de0893360ec77291b81716def9a5485f3243L23-R23) [[3]](diffhunk://#diff-bea93ce30a6591ac02edafbc55930343d7b39a88c8e73b1863b2cf0d59c0c186L29-R29)

These changes streamline workflow handling across editors and make future updates easier by centralizing the workflow logic and UI.

### CODE REVIEW

File: assets/js/src/core/components/workflow-card/components/dropdown-button/dropdown-button.tsx [hunk 1]
```diff
@@ -12,8 +12,8 @@ import React, { type ReactNode, useState, useEffect } from 'react'
 import { useTranslation } from 'react-i18next'
 import { Dropdown, type DropdownMenuProps } from '@Pimcore/components/dropdown/dropdown'
 import { Button } from '@Pimcore/components/button/button'
-import { useSubmitWorkflow } from '@Pimcore/modules/asset/editor/toolbar/workflow-log-modal/hooks/use-submit-workflow'
-import { useWorkflow } from '@Pimcore/modules/asset/editor/toolbar/workflow-log-modal/hooks/use-workflow'
+import { useSubmitWorkflow } from '@Pimcore/modules/element/editor/shared-components/workflow/log-modal/hooks/use-submit-workflow'
```
Comment (markus-moser) [inline assets/js/src/core/components/workflow-card/components/dropdown-button/dropdown-button.tsx:15]: Could you also please move the whole `workflow-card` component out of the components folder into the element modules folder?

It's not a component which should be in our storybook. Therefore we should move it and remove the story.

**Review by markus-moser — CHANGES_REQUESTED** [review]
Just one more thing, the rest LGTM! 👍

**Comment by xIrusux** [comment]
I also moved the workflow card :)  and will merge this now Thanks!
