### PR TITLE
[Classification Store] add import sort, fix refresh page behaviour and add delete icon

### LINKED ISSUE #3208: [Classificationstore] sort is missing
Sort option for columns is missing.

Image

### LINKED ISSUE #3209: [Classificationstore] search is missing
Search for keys is missing.

Image

### LINKED ISSUE #3210: [Classificationstore] refresh issues with paging
**Steps to reproduce**
- Login as admin
- Open the classificationstore
- Make sure you have 11 keys
- Navigate to page 2
- Delete the last entry

**Actual behaviour**
- Page is empty
- Refresh does not work

Image

**Expected behaviour**
- Page 1 with all entries should be shown

**Environment**

- Studio Nightly
- Windows
- Google Chrome

### LINKED ISSUE #3252: [Classdefinitions] delete icon is missing
In the classdefinitions for objects and enterprise metadata the delte icon is missing.

Image

### PR DESCRIPTION
**Pull request by xIrusux**
## Changes in this pull request
Resolves #3208 #3209 #3210 #3252

### CODE REVIEW

File: assets/js/src/core/modules/classification-store-config/components/store-editor/tabs/keys-tab.tsx [hunk 1]
```diff
@@ -64,15 +65,46 @@ export const KeysTab = ({ storeId }: IKeysTabProps): React.JSX.Element => {
   const [definitionModalOpen, setDefinitionModalOpen] = useState(false)
   const [page, setPage] = useState(1)
   const [pageSize, setPageSize] = useState(20)
+  const [searchTerm, setSearchTerm] = useState('')
```
Comment (Corepex) [inline assets/js/src/core/modules/classification-store-config/components/store-editor/tabs/keys-tab.tsx]:
```suggestion
  const [page, setPage] = useState<number>(1)
  const [pageSize, setPageSize] = useState<number>(20)
  const [searchTerm, setSearchTerm] = useState<string>('')
```

File: assets/js/src/core/modules/classification-store-config/components/store-editor/tabs/collections-tab.tsx [hunk 2]
```diff
@@ -57,15 +58,45 @@ export const CollectionsTab = ({ storeId }: ICollectionsTabProps): React.JSX.Ele
   const [selectedRows, setSelectedRows] = useState<RowSelectionState>({})
   const [page, setPage] = useState(1)
   const [pageSize, setPageSize] = useState(20)
+  const [searchTerm, setSearchTerm] = useState('')
```
Comment (Corepex) [inline assets/js/src/core/modules/classification-store-config/components/store-editor/tabs/collections-tab.tsx]:
```suggestion
  const [page, setPage] = useState<number>(1)
  const [pageSize, setPageSize] = useState<number>(20)
  const [searchTerm, setSearchTerm] = useState<string>('')
```

File: assets/js/src/core/modules/classification-store-config/components/store-editor/tabs/groups-tab.tsx [hunk 3]
```diff
@@ -57,15 +58,46 @@ export const GroupsTab = ({ storeId }: IGroupsTabProps): React.JSX.Element => {
   const [selectedRows, setSelectedRows] = useState<RowSelectionState>({})
   const [page, setPage] = useState(1)
   const [pageSize, setPageSize] = useState(20)
+  const [searchTerm, setSearchTerm] = useState('')
```
Comment (Corepex) [inline assets/js/src/core/modules/classification-store-config/components/store-editor/tabs/groups-tab.tsx]:
```suggestion
  const [page, setPage] = useState<number>(1)
  const [pageSize, setPageSize] = useState<number>(20)
  const [searchTerm, setSearchTerm] = useState<string>('')
```

**Review by Corepex — APPROVED** [review]
i added some types besides that everything is fine :) good job 🥇
