### PR TITLE
Menu re ordering 

### LINKED ISSUE #1792: Menu Improvements
https://www.figma.com/design/nF25XowM4BWrSv2ujvvCAd/WIP-Screens?node-id=1583-20699&t=Jrc8etDAps3Wq2dQ-4

- [ ] Wrong font name
- [ ] Updated menu structure: https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=12304-130526

### PR DESCRIPTION
**Pull request by xIrusux**
## Changes in this pull request
Resolves #1792 

[Screencast from 2025-08-12 15-28-04.webm](https://github.com/user-attachments/assets/6af7bc87-98b7-4b05-859d-15e47622531e)

This pull request introduces a significant reorganization and redesign of the main navigation system, both visually and structurally. The changes include a new navigation structure, updated icons, improved styling, and enhanced support for navigation item features such as dividers and avatars. The navigation items have been regrouped into new categories, and several modules have been repositioned accordingly. The visual appearance and usability of the main navigation have also been improved with updated styles and UI elements.

**Navigation Structure and Registry Updates:**

* Main navigation items have been restructured into new categories such as `QuickAccess`, `DataManagement`, `ExperienceEcommerce`, `AssetManagement`, `AutomationIntegration`, `Translations`, `Reporting`, and `System`, replacing the previous grouping (`File`, `Settings`, `Tools`, `Marketing`). Several modules have been repositioned under these new paths. (`assets/js/src/core/modules/app/base-layout/main-nav/index.ts`, `assets/js/src/core/modules/document-types/index.ts`, `assets/js/src/core/modules/email/index.ts`, `assets/js/src/core/modules/application-logger/index.ts`) [[1]](diffhunk://#diff-aa1921e91a8ea2b1f746b050046ebe85ee5feafa3f0b7c2790f69dc5807332fcL14-R65) [[2]](diffhunk://#diff-ea0c4392487e9a274b40257403655d50ecbd0d26935ef5bd1451e0304a84af1cL25-R28) [[3]](diffhunk://#diff-04185b9a888bda39aa9c686e02645aede1f60b7547fcb43842414750053cdf10L38-R46) [[4]](diffhunk://#diff-04185b9a888bda39aa9c686e02645aede1f60b7547fcb43842414750053cdf10L65-R66) [[5]](diffhunk://#diff-e6984f3550a7241bd78979953576297d7e727bfd7a5c9c7ceb14b1472f5867f9L25-R28)
* The `IMainNavItem` interface now supports a `dividerBottom` property, allowing for visual dividers between navigation items. (`assets/js/src/core/modules/app/base-layout/main-nav/services/main-nav-registry.ts`)
* The navigation hook and rendering logic have been updated to support the new `dividerBottom` property and maintain correct child sorting. (`assets/js/src/core/modules/app/base-layout/main-nav/hooks/use-main-nav.ts`, `assets/js/src/core/modules/app/base-layout/main-nav/main-nav.tsx`) [[1]](diffhunk://#diff-11707ce5bb84a67c03eda8ec00ed0307349f108d19bada2474351f4b6ce441cdR44) [[2]](diffhunk://#diff-11707ce5bb84a67c03eda8ec00ed0307349f108d19bada2474351f4b6ce441cdL62-R64) [[3]](diffhunk://#diff-fbb774caac4c7d91a46404e9efe73e1ad4af2a03bf7c8824fa7d710118ffaea4R67-R71) [[4]](diffhunk://#diff-fbb774caac4c7d91a46404e9efe73e1ad4af2a03bf7c8824fa7d710118ffaea4R105-R106)

**Visual and UI Enhancements:**

* Navigation styles have been overhauled: navigation width, padding, and spacing have been adjusted, and new styles for avatars, dividers, and sub-headers have been added. (`assets/js/src/core/modules/app/base-layout/main-nav/main-nav.styles.ts`) [[1]](diffhunk://#diff-ecc0817ec480c805e250ce4dc06e3125746e5396232147de72f12f763f7a322cL26-R26) [[2]](diffhunk://#diff-ecc0817ec480c805e250ce4dc06e3125746e5396232147de72f12f763f7a322cL66-R75) [[3]](diffhunk://#diff-ecc0817ec480c805e250ce4dc06e3125746e5396232147de72f12f763f7a322cL96) [[4]](diffhunk://#diff-ecc0817ec480c805e250ce4dc06e3125746e5396232147de72f12f763f7a322cR128-R147) [[5]](diffhunk://#diff-ecc0817ec480c805e250ce4dc06e3125746e5396232147de72f12f763f7a322cL137-R165)
* Navigation items now display their icons inside `Avatar` components for a more modern look. (`assets/js/src/core/modules/app/base-layout/main-nav/main-nav.tsx`) [[1]](diffhunk://#diff-fbb774caac4c7d91a46404e9efe73e1ad4af2a03bf7c8824fa7d710118ffaea4L11-R11) [[2]](diffhunk://#diff-fbb774caac4c7d91a46404e9efe73e1ad4af2a03bf7c8824fa7d710118ffaea4L84-R96)
* A sub-header with a divider is shown for the `QuickAccess` navigation group. (`assets/js/src/core/modules/app/base-layout/main-nav/main-nav.tsx`)

**Icon Library Updates:**

* New icons have been added for the new navigation categories (`quick-access`, `data-object`, `experience-commerce`, `automation-integration`, `reporting`) and registered in the icon library. (`assets/js/src/core/modules/icon-library/index.ts`) [[1]](diffhunk://#diff-33ba570ecf21d470d66355be8d1750398af7faf2c03cae6b586efff55197cb26R32) [[2]](diffhunk://#diff-33ba570ecf21d470d66355be8d1750398af7faf2c03cae6b586efff55197cb26R101) [[3]](diffhunk://#diff-33ba570ecf21d470d66355be8d1750398af7faf2c03cae6b586efff55197cb26R183-R191) [[4]](diffhunk://#diff-33ba570ecf21d470d66355be8d1750398af7faf2c03cae6b586efff55197cb26R301-R304) [[5]](diffhunk://#diff-33ba570ecf21d470d66355be8d1750398af7faf2c03cae6b586efff55197cb26R577-R580) [[6]](diffhunk://#diff-33ba570ecf21d470d66355be8d1750398af7faf2c03cae6b586efff55197cb26R905-R908) [[7]](diffhunk://#diff-33ba570ecf21d470d66355be8d1750398af7faf2c03cae6b586efff55197cb26R937-R940)

**Module Imports and Bootstrap:**

* The order and presence of module imports in the application bootstrap have been updated to match the new navigation structure. (`assets/js/src/core/bootstrap.ts`)

These changes collectively modernize the navigation experience and lay the groundwork for a more scalable and user-friendly main navigation system.

### CODE REVIEW

File: assets/js/src/core/modules/app/base-layout/main-nav/hooks/use-main-nav.ts [hunk 1]
```diff
@@ -37,10 +37,11 @@ const addNavItemToItemList = (items: IMainNavItem[], item: IMainNavItem): void =
 
     if (existingItem === undefined) {
       existingItem = {
-        order: isCurrentItem ? item.order : 100,
+        order: isCurrentItem ? item.order : 1000,
         id: level,
         label: item.label ?? level,
         path: levels.slice(0, index + 1).join('/'),
+        dividerBottom: item.dividerBottom ?? undefined,
```
Comment (Corepex) [inline assets/js/src/core/modules/app/base-layout/main-nav/hooks/use-main-nav.ts]:
```suggestion
        dividerBottom: item.dividerBottom ?? false,
```

If `dividerBottom` is a boolean - we should set it to false (as default case - or)?

https://github.com/pimcore/studio-ui-bundle/pull/1856/files?show-vendored-files=false#diff-5aefae5e9e9fcc0a97d0268b4a9379cc96b7afb9151dbf183385e9d404ce97e6R21

File: assets/js/src/core/modules/app/base-layout/main-nav/main-nav.styles.ts [hunk 2]
```diff
@@ -125,18 +125,44 @@ export const useStlyes = createStyles(({
...
+      text-align: left;
+      color: ${token.colorTextTreeElement};
+      font-size: ${token.fontSize}px;
+      font-family:  ${token.fontFamily};
+      padding: ${token.paddingXS}px ${token.paddingXS}px ${token.paddingXS}px ${token.paddingXXS}px;
+
+      &.main-nav__list-detail-divider {
+        border-bottom: 1px solid ${token.colorFillSecondary};
+      }
+      }
```
Comment (Corepex) [inline assets/js/src/core/modules/app/base-layout/main-nav/main-nav.styles.ts]:
```suggestion
      .main-nav__list-detail-sub-header {
        width: 100%;
        height: 42px;
        text-align: left;
        color: ${token.colorTextTreeElement};
        font-size: ${token.fontSize}px;
        font-family:  ${token.fontFamily};
        padding: ${token.paddingXS}px ${token.paddingXS}px ${token.paddingXS}px ${token.paddingXXS}px;

        &.main-nav__list-detail-divider {
          border-bottom: 1px solid ${token.colorFillSecondary};
        }
      }
```

File: assets/js/src/core/modules/app/base-layout/main-nav/main-nav.styles.ts [hunk 3]
```diff
@@ -125,18 +125,44 @@ export const useStlyes = createStyles(({
...
         align-items: center;
-        gap: ${token.marginXXS}px;
+        font-size: ${token.fontSize}px;
         min-height: 46px;
-        
+        font-family:  ${token.fontFamily};
+
+        .plain-icon {
+        margin: 4px;
+        }
```
Comment (Corepex) [inline assets/js/src/core/modules/app/base-layout/main-nav/main-nav.styles.ts]:
```suggestion
        .plain-icon {
          margin: 4px;
        }
```

File: assets/js/src/core/modules/app/base-layout/main-nav/main-nav.tsx [hunk 4]
```diff
@@ -27,6 +27,7 @@ export const MainNav = (): React.JSX.Element => {
   const { t } = useTranslation()
   const { styles } = useStlyes()
   const { navItems } = useMainNav()
+
```
Comment (Corepex) [inline assets/js/src/core/modules/app/base-layout/main-nav/main-nav.tsx]:
```suggestion
```

**Review by Corepex — APPROVED** [review]
LGTM - the "new" menu now looks much cleaner. I absolutly love the small circle behind the icons 😍  - GJ

File: assets/js/src/core/modules/app/base-layout/main-nav/hooks/use-main-nav.ts (hunk 1 above)
Comment (xIrusux) [reply assets/js/src/core/modules/app/base-layout/main-nav/hooks/use-main-nav.ts]: hm my idea was that it would me omitted as a prop if its not defined just like it was originally passed in - but I found a better way that cleans it up. :) good catch !
