### PR TITLE
Global notes events

### LINKED ISSUE #161: Global Notes & Events view
Paginated Notes Listing with filter and fieldFilters: http://localhost/pimcore-studio/api/docs#/Notes/note_get_collection

(Maybe we should switch this to a post request, since we send json in the query for the fieldFilters)

Delete notes
http://localhost/pimcore-studio/api/docs#/Notes/note_delete_by_id

### LINKED ISSUE #979: Image preview does not get refreshed after editing an image
**Steps to reproduce**

- Login as admin
- Open an image
- Edit the image
- Save the edited image
- Open the preview

**Actual behaviour**

- Changes should be seen on the preview page
- Refresh button has no effect
- Changes are seen after a browser refresh

**Expected behaviour**

- Changes should be seen immediately in the preview tab

**Environment**

- Studio nightly
- Windows
- Google Chrome

### PR DESCRIPTION
**Pull request by xIrusux**
## Changes in this pull request
Resolves #161

## Additional info

First PR for global notes and events container 

https://github.com/user-attachments/assets/5064b2c2-bbb5-4b35-bafb-16bf2a8df3c7

Next: 
- shared component for this layout 
- allow showing different kinds of details data

### CODE REVIEW

File: assets/js/src/core/modules/notes-and-events/notes-and-events-container.tsx [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+              gap={ 'medium' }
+              vertical
+            >
+              <Flex
+                justify={ 'space-between' }
+              >
+                <Flex
+                  gap={ 'small' }
+                >
+                  <Title>Notes & Events</Title>
```
Comment (ValeriaMaltseva) [inline assets/js/src/core/modules/notes-and-events/notes-and-events-container.tsx]: Should we translate this?

File: assets/js/src/core/modules/notes-and-events/table/note-modal.tsx [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+      <>
+        {displayTextArea(noteDetail.type, t('notes-and-events.columns.type'))}
+        {displayTextArea(noteDetail.title, t('notes-and-events.columns.title'))}
+        {displayTextArea(noteDetail.description, t('notes-and-events.columns.description'), false)}
+        {displayTextArea(noteDetail.fields.toString(), t('notes-and-events.columns.details'))}
+        {isString(noteDetail.userName) && displayTextArea(noteDetail.userName, t('notes-and-events.columns.user'))}
+        <Box
+          margin={ 'small' }
+        >
+          <div>Date</div>
```
Comment (ValeriaMaltseva) [inline assets/js/src/core/modules/notes-and-events/table/note-modal.tsx]: Should we translate this?

File: assets/js/src/core/modules/notes-and-events/table/table.tsx [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+  const [notes, setNotes] = useState<DataNote[]>([])
+  const [noteDetail, setNoteDetail] = useState<DataNote | undefined>(undefined)
+
+  useEffect(() => {
+    if (notesAndEvents !== undefined && Array.isArray(notesAndEvents)) {
+      setNotes(enrichNotesAndEvents(notesAndEvents))
+    }
+  }, [notesAndEvents])
+
+  const enrichNotesAndEvents = (data: Note[]): DataNote[] => {
```
Comment (ValeriaMaltseva) [inline assets/js/src/core/modules/notes-and-events/table/table.tsx]: Can just simplify 😉

```
const enrichNotesAndEvents = (data: Note[]): DataNote[] => (
    data.map((item) => ({
      ...item,
      fields: item.data.length,
      rowId: uuid()
    }))
  )
```

File: assets/js/src/core/modules/notes-and-events/table/table.tsx [hunk 4]
```diff
@@ -0,0 +1,186 @@
...
+          <Flex
+            align='center'
+            className='w-full'
+            justify='center'
+          >
+            <IconButton
+              icon={ { value: 'open-folder' } }
+              onClick={ async () => {
+                !isUndefined(elementType) &&
+                                await openElement({
```
Comment (ValeriaMaltseva) [inline assets/js/src/core/modules/notes-and-events/table/table.tsx:145]: What do you think about moving this into a separate function to avoid duplication?

**Review by ValeriaMaltseva — APPROVED** [review]
It looks pretty good already! 😊

I've added some points, but it is not a blocker, and you can fix them in the next PR regarding the Notes and Events.

File: assets/js/src/core/modules/notes-and-events/notes-and-events-container.tsx (hunk 1 above)
Comment (xIrusux) [reply assets/js/src/core/modules/notes-and-events/notes-and-events-container.tsx]: uh that was an oversight. Thanks

File: assets/js/src/core/modules/notes-and-events/table/note-modal.tsx (hunk 2 above)
Comment (xIrusux) [reply assets/js/src/core/modules/notes-and-events/table/note-modal.tsx]: same :)

File: assets/js/src/core/modules/notes-and-events/table/table.tsx (hunk 3 above)
Comment (xIrusux) [reply assets/js/src/core/modules/notes-and-events/table/table.tsx]: simplified

File: assets/js/src/core/modules/notes-and-events/table/table.tsx (hunk 4 above)
Comment (xIrusux) [reply assets/js/src/core/modules/notes-and-events/table/table.tsx:145]: hm I see what you mean. I saw it more as a is not null check and then the function call which is the same in 2 places. If there are more calls I will change it.
