### PR TITLE
Fixed version tab render issue

### LINKED ISSUE #646: [Bug] adding a delete action results in an error
**Steps to reproduce**

- Login as admin
- Open an image editor
- Switch to the scheduler
- Add an entry to delete a specific version

**Actual behaviour**
Image
- After saving an error is thrown
- Entry is saved

**Expected behaviour**
- Saving is done without an error

**Environment**

- Nightly build

### PR DESCRIPTION
**Pull request by Corepex**
## Changes in this pull request
Resolves #646 and #651

## Additional info
This pull request includes changes to the `create-version-accordion-item-functions.tsx` file to replace `useTranslation` with `i18n` for translation functionality and to refactor the component structure. Additionally, there is a minor formatting change in the `versions-container.tsx` file.

Translation changes:

* Replaced `useTranslation` with `i18n` for all translation calls in `create-version-accordion-item-functions.tsx` [[1]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176L21-R27) [[2]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176L55-L58) [[3]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176L94-R91) [[4]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176L104-R101) [[5]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176L119-R116) [[6]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176L128-R133) [[7]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176L164-R169) [[8]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176L180-R181) [[9]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176L189-R190).

Component refactoring:

* Moved state management for `deletingVersion` and `publishingVersion` into a new `Component` function within `create-version-accordion-item-functions.tsx` [[1]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176L128-R133) [[2]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176L145-R146) [[3]](diffhunk://#diff-4b1bbebfef40e6e019bce57109205af12a368b8e6b412edd36a605a7afe1d176R201-R209).

Formatting change:

* Adjusted the import statement formatting in `versions-container.tsx` for better readability.

### CODE REVIEW

File: assets/js/src/core/modules/element/editor/shared-tab-manager/tabs/versions/create-version-accordion-item-functions.tsx [hunk 1]
```diff
@@ -91,17 +87,18 @@ export const createVersionAccordionItem = ({
...
+          dateStyle: 'short',
+          timeStyle: 'medium'
+        })}`}</span>
     </div>
   )
 
   const subtitle = (
     <div>
-      <span className={ 'sub-title' }>{`${t('by')} ${version.user?.name ?? ''}`}</span>
+      <span className={ 'sub-title' }>{`${i18n.t('by')} ${version.user?.name ?? ''}`}</span>
```
Comment (vin0401) [inline assets/js/src/core/modules/element/editor/shared-tab-manager/tabs/versions/create-version-accordion-item-functions.tsx]: We should still use the useTranslation hook. Otherwise we loose the reactivity from react and would encounter some issues here the moment we implement the switching of the language.

**Review by vin0401 — CHANGES_REQUESTED** [review]

File: assets/js/src/core/modules/element/editor/shared-tab-manager/tabs/versions/create-version-accordion-item-functions.tsx (hunk 1 above)
Comment (Corepex) [reply assets/js/src/core/modules/element/editor/shared-tab-manager/tabs/versions/create-version-accordion-item-functions.tsx]: good point, i converted everything to components (see: https://github.com/pimcore/studio-ui-bundle/pull/744/commits/62a163d030d228e76f5a705c8086277a9859df40)

**Review by vin0401 — APPROVED** [review]
