### PR TITLE
Added fixed names to crm fields

### LINKED ISSUE #3227: [Class editor] some crm fields are missing the name
Some CRM fields can not be added to a class as the name is read only and empty. In classic UI the name is prefilled.

- First name
- Last name
- Email
- Gender

Image

### PR DESCRIPTION
**Pull request by Corepex**
## Changes in this pull request
Resolves #3227

## Additional info
This pull request adds a new `getDefaultData` method to several dynamic type field definition classes, ensuring that each field type returns a default data object with a specific `name` property. Additionally, it updates imports to include the `FieldDefinitionData` type where necessary. These changes improve consistency and type safety across dynamic field definitions.

### Dynamic Type Field Definitions: Default Data

* Added a `getDefaultData` method to the following classes to return a default data object with the appropriate `name` property:
  - `DynamicTypeFieldDefinitionEmail` now returns `{ ...super.getDefaultData(), name: 'email' }`
  - `DynamicTypeFieldDefinitionFirstname` now returns `{ ...super.getDefaultData(), name: 'firstname' }`
  - `DynamicTypeFieldDefinitionLastname` now returns `{ ...super.getDefaultData(), name: 'lastname' }`
  - `DynamicTypeFieldDefinitionGender` now returns `{ ...super.getDefaultData(), name: 'gender' }`

### Type Import Improvements

* Updated imports in all affected files to include the `FieldDefinitionData` type from the abstract data definition module, improving type safety and code clarity. [[1]](diffhunk://#diff-62c9cc201ca03edf534a7e91ba185a6f853e03fdf997eef25b6cfabece3d609cL12-R12) [[2]](diffhunk://#diff-00f15aa9cf2f8e62f7b7d8d185602b016da34b95f5d32d963ab8dc52bffb5a8fL12-R12) [[3]](diffhunk://#diff-06f5e85d0328ed47b040e3c504cea38cfbafb1f4610c199e1f22f7f118b3d908L12-R12) [[4]](diffhunk://#diff-ebd63e1aa466447edd57ccdf5049c93e1739b7852a6091f139268ee456dceb39L12-R12)

### CODE REVIEW

File: assets/js/src/core/modules/field-definitions/dynamic-types/types/data/firstname/dynamic-type-field-definition-firstname.tsx [hunk 1]
```diff
@@ -21,6 +21,13 @@ export class DynamicTypeFieldDefinitionFirstname extends DynamicTypeFieldDefinit
     return { type: 'name', value: 'name' }
   }
 
+  getDefaultData (): FieldDefinitionData {
+    return {
+      ...super.getDefaultData(),
+      name: 'firstname'
```
Comment (markus-moser) [inline assets/js/src/core/modules/field-definitions/dynamic-types/types/data/firstname/dynamic-type-field-definition-firstname.tsx]: Could you please also fill out the title field with a translated title like here (for all fields)?
https://github.com/pimcore/admin-ui-classic-bundle/blob/2.3/public/js/pimcore/object/classes/data/firstname.js#L36

**Review by markus-moser — CHANGES_REQUESTED** [review]
I just noticed that in the classic UI we also automatically fill the title. Please let's add this, afterwards I'd say its ok to merge it!

File: assets/js/src/core/modules/field-definitions/dynamic-types/types/data/firstname/dynamic-type-field-definition-firstname.tsx (hunk 1 above)
Comment (Corepex) [reply assets/js/src/core/modules/field-definitions/dynamic-types/types/data/firstname/dynamic-type-field-definition-firstname.tsx]: I've implemented the default value for the `title` fields in https://github.com/pimcore/studio-ui-bundle/pull/3278/commits/a6dc4ac86db2bc7685eeb7af769afa2c8a052cf8. 

I created a new translation key for the title (`field-definition.crm.lastname.title`) - if you like it better, we can also use the generic one (`field-definition.lastname`)
