### PR TITLE
[Data Object Editor] Moving field collections doesn't work

### LINKED ISSUE #1253: [Data Object Editor] Moving field collections doesn't work
add some field collection entries

Image

move them around - just title changes, but not the content

Image

### PR DESCRIPTION
**Pull request by ValeriaMaltseva**
## Changes in this pull request
Resolves #1253

### CODE REVIEW

**Comment by markus-moser** [comment]
Data types which I tested and didn't find a problem:
- Date picker
- Date range picker
- Time picker
- Geo Point
- Geo Polygon
- Geo Polyline
- Numeric Range
- Slider
- Boolean Select
- Checkbox
- External Image
- Hotspot Image
- Image
- Link
- Table
- Video

File: assets/js/src/core/components/geo-bounds-drawer/geo-bounds-drawer.tsx [hunk 1]
```diff
@@ -22,24 +23,29 @@ export interface GeoBoundsDrawerProps extends GeoMapCardBaseProps {
 }
 
 export const GeoBoundsDrawer = ({ ...props }: GeoBoundsDrawerProps): React.JSX.Element => {
-  const [mapValue, setMapValue] = React.useState<GeoBounds | undefined>(props.value ?? undefined)
-  const [footerValue, setFooterValue] = React.useState<GeoBounds | undefined>(props.value ?? undefined)
+  const [mapValue, setMapValue] = useState<GeoBounds | undefined>(props.value ?? undefined)
```
Comment (markus-moser) [inline assets/js/src/core/components/geo-bounds-drawer/geo-bounds-drawer.tsx:26]: For some reason the geo bounds map re-renders during changing of the geo bounds rectangle before clicking "save" within the map. Also for other types like e.g. the poly drawer the behaviour changed with this PR. So we re-render the map after value change (and therefore center the drawed element after changing the value). The way how it is implemented in the polygon is fine and re-centering it after value change is even an advantage. But for the geo bounds it's really strange at the moment.

**Comment by markus-moser** [comment]
I found an a bit related issue to this PR regarding the geo types:
- https://github.com/pimcore/studio-ui-bundle/issues/1632

File: assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/image-gallery/image-gallery.tsx [hunk 2]
```diff
@@ -79,7 +79,8 @@ const removeKeys = (items: ImageGalleryValue): ImageGalleryValue => {
 }
 
 export const ImageGallery = (props: ImageGalleryProps): React.JSX.Element => {
-  const [value, setValueState] = useState<ImageGalleryValue>(addKeys(props.value ?? []))
+  const imageValue = addKeys(props.value ?? [])
```
Comment (markus-moser) [inline assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/image-gallery/image-gallery.tsx]: The images within the gallery somehow flash now when changing the value. E.g. when sorting the images via drag&drop. This doesn't happen on the nightly. Is this because we have the production build on the nightly or does this PR cause the problem?

File: assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/structured-table/structured-table.tsx [hunk 3]
```diff
@@ -86,15 +81,17 @@ export const StructuredTable = (props: StructuredTableProps): React.JSX.Element
...
     if (value !== null) {
       const newValue = value
+
       for (const rowKey in value) {
         for (const colKey in value[rowKey]) {
           newValue[rowKey][colKey] = castColumnValue(null, colKey)
         }
       }
-      setValue(newValue)
+
```
Comment (markus-moser) [inline assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/structured-table/structured-table.tsx]: For some reason the empty value does not work. It does not trigger the onChange logic. Maybe we need to create a copy of the value here as otherwise we use the same reference to the value object?

File: assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/url-slug/url-slug.tsx [hunk 4]
```diff
@@ -42,13 +42,12 @@ const getInitialValue = (value?: UrlSlugEntry[] | null): UrlSlugEntry[] => {
 }
 
 export const UrlSlug = (props: UrlSlugProps): React.JSX.Element => {
-  const initialValue = getInitialValue(props.value)
+  const value = getInitialValue(props.value)
```
Comment (markus-moser) [inline assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/url-slug/url-slug.tsx:45]: The URL slug is broken now. When multiple sites are involved it behaves very strange.

**Review by markus-moser — CHANGES_REQUESTED** [review]
I tested all contained data types and in general it looks really good. I found some problems, see my comments.

Didn't actually test in detail if thes solves the moving field collections problem. Please ask Patrick at the end to test it.

Did you also test the other data types like relations, quantity value etc.?

File: assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/image-gallery/image-gallery.tsx (hunk 2 above)
Comment (ValeriaMaltseva) [reply assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/image-gallery/image-gallery.tsx]: The problem was with the keys. With the previous approach, they were recreated on each render.

File: assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/url-slug/url-slug.tsx (hunk 4 above)
Comment (ValeriaMaltseva) [reply assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/url-slug/url-slug.tsx:45]: Created the issue as a separate task: https://github.com/pimcore/studio-ui-bundle/issues/1636

File: assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/image-gallery/image-gallery.tsx (hunk 2 above)
Comment (markus-moser) [reply assets/js/src/core/modules/element/dynamic-types/definitions/objects/data-related/components/image-gallery/image-gallery.tsx]: The image gallery is broken now. When I sort items they do not get resorted. Also when I add a new item inbetween other items it does not work. Could you please check it once again?

**Review by markus-moser — CHANGES_REQUESTED** [review]
Please check my comment for the image gallery. The rest LGTM!

**Review by markus-moser — APPROVED** [review]
LGTM now 👍 

Maybe you could ask Patrick also to test it a bit?

**Comment by ValeriaMaltseva** [comment]
@markus-moser Thanks a lot for testing my PR! I will ask Patrick to test it.
