### PR TITLE
Fix element icons

### LINKED ISSUE #68: Element Icons
- icons per element type
- custom icons for custom element types (e.g. custom asset types, data object classes) 
   - project specific icons should be possible

### PR DESCRIPTION
**Pull request by Corepex**
## Changes in this pull request
Resolves #68 

## Additional info
This pull request includes several changes aimed at improving the handling of icons and streamlining the data object processing. The most important changes include adding a new method for rendering icons, updating the data object helper to simplify data extraction, and cleaning up the handling of node icons.

Improvements to icon handling:

* [`assets/js/src/core/components/icon/icon.tsx`](diffhunk://#diff-466272bf4c5b7b260e3fde2cc6c4cbb6009c3d2c323bbe8df94525d59d0014f4L27-R63): Added a new method `renderIcon` to handle both SVG and file-based icons, ensuring proper rendering based on the icon type.

Streamlining data object processing:

* [`assets/js/src/core/modules/data-object/hooks/use-data-object-helper.ts`](diffhunk://#diff-85be3e81894bbf00e4281cecf66d2d7dde5eecc1d36a34cca14c46eaf06cd94bL40-R44): Simplified the data extraction process by directly destructuring the `data` object from the API response.

Cleanup and debugging:

* [`assets/js/src/core/components/element-tree/node/tree-node.tsx`](diffhunk://#diff-ddbe3676768e64bca995d5dc624d29161fa84d0b42f1093c102a8abf5960f9c2R85-R86): Added a console log for debugging the `icon` property.
* [`assets/js/src/core/modules/data-object/tree/hooks/use-node-api-hook.ts`](diffhunk://#diff-26f91edce5cc0d7f7beaddf257ba8b68af858d0a935c66e5512f1f830dfff137L49-R57): Added a console log for debugging the `icon` property and updated the logic for determining the icon value.
* [`assets/js/src/core/modules/widget-manager/widget-manager-slice.ts`](diffhunk://#diff-636cd5627d95adaf17ec5845d46c1f7a1240ffb32cf343cc32bb7ef712f74ffbR88-R89): Added a console log for debugging the `data` payload in the widget manager slice.

### CODE REVIEW

File: assets/js/src/core/components/icon/icon.tsx [hunk 1]
```diff
@@ -24,24 +24,43 @@ export interface IconProps {
...
 export const Icon = ({ name, options, className }: IconProps): React.JSX.Element => {
   const iconLibrary = useInjection<IconLibrary>(serviceIds.iconLibrary)
-  const SvgIcon = iconLibrary.get(name)
   const width = options?.width ?? 16
   const height = options?.height ?? 16
 
-  if (SvgIcon === undefined) {
-    return <div style={ { width, height } } />
+  const renderIcon = (): React.JSX.Element => {
+    const isFile = name.endsWith('.svg')
```
Comment (markus-moser) [inline assets/js/src/core/components/icon/icon.tsx]: We shouldn't do it like this but reflect the original icon type which comes from the server ;)

File: assets/js/src/core/modules/data-object/tree/hooks/use-node-api-hook.ts [hunk 2]
```diff
@@ -46,10 +46,13 @@ export const useNodeApiHook = (node: TreeNodeProps): NodeApiHookReturnType => {
 
     const dataObjectData = data.items
     dataObjectData.forEach((dataObjectNode) => {
-      const icon = dataObjectNode.icon?.type === 'name' ? dataObjectNode.icon?.value : 'mainObject'
+      const icon = dataObjectNode.icon?.value === '' || dataObjectNode.icon?.value === 'vector'
```
Comment (markus-moser) [inline assets/js/src/core/modules/data-object/tree/hooks/use-node-api-hook.ts]: We have some more complexity in there. In the response from the server (for both assets and data-objects) we can get an icon via 'customAttributes.icon'. If an icon is defined there it will overrule the regular icon. The format of the icon is the same like for the regular one (with type + icon properties). The background for this case are our events. When the icon is overruled via event the change will be added to the customAttributes.

**Review by markus-moser — APPROVED** [review]
