### PR TITLE
1605 refresh props fix

### LINKED ISSUE #1605: [Predefined Properties] refreshing properties list not working
**Steps to reproduce**

- Login as admin
- Open the predefined properties list
- Add a predefined property
- Close the properties list
- Open the list once again

**Actual behaviour**
- New property is not shown without a browser refresh

**Expected behaviour**
- New property should be shown

**Environment**

- Studio Nightly
- Windows
- Google Chrome

### PR DESCRIPTION
**Pull request by xIrusux**
## Changes in this pull request
Resolves #1605

### CODE REVIEW

File: assets/js/src/core/modules/background-processor/services/background-processor.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export class BackgroundProcessor {
       throw new Error(`Process with name ${processName} does not exist.`)
     }
 
-    this.startProcess(processName)
+    // this.startProcess(processName)
```
Comment (Corepex) [inline assets/js/src/core/modules/background-processor/services/background-processor.ts]: i guess that happend by accident ....

File: assets/rsbuild.config.ts [hunk 2]
```diff
@@ -21,17 +21,19 @@ let env: 'development' | 'production' = 'production';
 const isDevServer = nodeEnv === 'dev-server';
 if (nodeEnv !== env) {
```
Comment (Corepex) [inline assets/rsbuild.config.ts]: This file shouldn`t be committed

File: assets/rsbuild.sdk.config.ts [hunk 3]
```diff
@@ -34,11 +34,15 @@ if (nodeEnv !== env) {
 export default defineConfig({
```
Comment (Corepex) [inline assets/rsbuild.sdk.config.ts]: This file shouldn`t be committed ...

**Review by Corepex — CHANGES_REQUESTED** [review]

File: assets/js/src/core/modules/predefined-properties/predefined-properties-container.tsx [hunk 4]
```diff
@@ -46,6 +52,12 @@ export const PredefinedPropertiesContainer = (): React.JSX.Element => {
     }
   }, [predefinedProperties])
 
+  useEffect(() => {
+    if (isError) {
```
Comment (Corepex) [inline assets/js/src/core/modules/predefined-properties/predefined-properties-container.tsx]: use it the following way

```jsx
if(!isUndefined(error)) {
  trackError(new ApiError(error))
}
```

dont forget to remove `isError` and change the `useEffect` dependency

Comment (Corepex) [reply assets/js/src/core/modules/predefined-properties/predefined-properties-container.tsx]: `isUndefined` from loadash

**Review by Corepex — APPROVED** [review]
LGTM
