### PR TITLE
Restricted lock options to admins only

### LINKED ISSUE #968: Lock folder, objects should not be shown for non admin users
**Steps to reproduce**

- Login with a non admin user
- Open the context menu on an asset folder

**Actual behaviour**

- Lock option is shown for non admin user

Image

**Expected behaviour**

- Lock option should not be available for non admin user

**Environment**

- Studio nightly
- Windows
- Google Chrome

### PR DESCRIPTION
**Pull request by Corepex**
## Changes in this pull request
Resolves #968

## Additional info
This pull request includes changes to the `use-lock.tsx` file to integrate user information and adjust the visibility of lock-related actions based on user permissions. The most important changes include importing necessary user-related modules, retrieving the current user state, and modifying the visibility conditions for lock and unlock actions.

**Integration of user information and permission checks:**

* [`assets/js/src/core/modules/element/actions/lock/use-lock.tsx`](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2R22-R24): Imported `store`, `selectCurrentUser`, and `UserInformation` from user-related modules.

* [`assets/js/src/core/modules/element/actions/lock/use-lock.tsx`](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2R42-R43): Retrieved the current user state using `store.getState()` and `selectCurrentUser`.

* [`assets/js/src/core/modules/element/actions/lock/use-lock.tsx`](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2L76-R81): Modified the visibility condition of the lock action to hide it if the user is not an admin. [[1]](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2L76-R81) [[2]](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2L88-R93) [[3]](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2L101-R106) [[4]](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2L113-R118)

* [`assets/js/src/core/modules/element/actions/lock/use-lock.tsx`](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2L126-R131): Modified the visibility condition of the unlock action to hide it if the user is not an admin. [[1]](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2L126-R131) [[2]](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2L138-R143) [[3]](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2L151-R156) [[4]](diffhunk://#diff-0fa3f9405e5a8f51366aed10a4f619abaf0f85b8de93920fe27b3c100d9b53a2L163-R168)

### CODE REVIEW

File: assets/js/src/core/modules/element/actions/lock/use-lock.tsx [hunk 1]
```diff
@@ -36,6 +39,8 @@ export interface UseLockHookReturn {
 }
 
 export const useLock = (elementType: ElementType): UseLockHookReturn => {
+  const state = store.getState()
+  const user = selectCurrentUser(state as { [userSliceName]: UserInformation })
```
Comment (markus-moser) [inline assets/js/src/core/modules/element/actions/lock/use-lock.tsx]: Please use the `useUser` use hook which you created some time ago to retrieve the user. This would simplify and centralize the approach a bit.

**Review by markus-moser — CHANGES_REQUESTED** [review]

**Review by markus-moser — APPROVED** [review]

**Review by markus-moser — APPROVED** [review]
